server {
    listen 80;
    listen [::]:80;
    server_name xgbbing.win www.xgbbing.win;
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    # 监听 8090，开启 SSL，并启用 PROXY Protocol（从 Xray 获取真实 IP）
    listen 8090 ssl proxy_protocol;
    # 监听 IPv6
    listen [::]:8090 ssl proxy_protocol;

    http2 on;

    server_name xgbbing.win www.xgbbing.win;

    # 信任 Docker 默认的内网 IP 段（172.x.x.x）
    set_real_ip_from 172.0.0.0/8;

    # 信任 Docker 的 IPv6 内网段（一般默认是 fe80::/10 或 fd00::/8，视你的 docker 配置而定）
    set_real_ip_from fe80::/10;
    set_real_ip_from fd00::/8;

    # 从 PROXY Protocol 中获取用户真实 IP
    real_ip_header proxy_protocol;

    ssl_certificate /etc/letsencrypt/live/xgbbing.win/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xgbbing.win/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # 代理后端 API 请求
    location /api {
        # 容器间用容器名通信，比如容器名 node
        proxy_pass http://node:3000;

        # 携带真实请求头信息 (很重要，让 Node.js 能获取客户端真实 IP 等)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 如果你的应用使用 WebSocket，需要加上这两行
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
    }

    # 前端项目 app1
    location ^~ /app1/ {
        alias /usr/share/nginx/html/app1/;
        index index.html;
        try_files $uri $uri/ /app1/index.html;
        add_header Cache-Control "no-cache";
    }
    # 兼容不带 /
    location = /app1 {
        return 301 https://$host$request_uri/;
    }

    # 前端项目 app2
    location ^~ /app2/ {
        alias /usr/share/nginx/html/app2/;
	      index index.html;
        try_files $uri $uri/ /app2/index.html;
        add_header Cache-Control "no-cache";
    }
    # 兼容不带 /
    location = /app2 {
       return 301 https://$host$request_uri/;
    }

    location ^~ /docs/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    # 前端项目 主页
    location / {
        root /usr/share/nginx/html/home;
        index index.html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }
    
}